import { WebTwain } from 'dwt/dist/types/WebTwain';
import dynamic from 'next/dynamic';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react';

const DWT = dynamic(() => import("../components/DWT"), {
  ssr: false
});

export default function Home() {
  const [initialized,setInitialized] = React.useState(false);
  const DWObject = React.useRef<WebTwain>();
  const onWebTWAINReady = (dwtObject:WebTwain) => {
    DWObject.current = dwtObject;
    setInitialized(true);
  }
  const scan = () => {
    if (DWObject.current) {
      DWObject.current.SelectSource(function () {
        DWObject.current!.OpenSource();
        DWObject.current!.AcquireImage();
      },
        function () {
          console.log("SelectSource failed!");
        }
      );
    }
  }
  const save = () => {
    if (DWObject.current) {
      DWObject.current.SaveAllAsPDF("Scanned");
    }
  }
  return (
    <>
      <Head>
        <title>Next.js Document Scanner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h2>Document Scanner</h2>
          {initialized
            ? <>
                <button onClick={scan}>Scan</button>
                <button onClick={save}>Save</button>
              </>
            : <>
                <p>Initializing...</p>
              </>
          }
          
          <div className={styles.container}>
            <DWT
              width='100%'
              height='100%'
              viewMode={{cols:2,rows:2}}
              onWebTWAINReady={onWebTWAINReady}
            ></DWT>
          </div>
        </div>
      </main>
    </>
  )
}
