import dynamic from 'next/dynamic';
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const DWT = dynamic(() => import("../components/DWT"), {
  ssr: false,
  loading: () => <p>Initializing Document Scanner</p>,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js Document Scanner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h2>Document Scanner</h2>
          <div className={styles.container}>
            <DWT
              width='100%'
              height='100%'
            ></DWT>
          </div>
        </div>
      </main>
    </>
  )
}
